services:
  #Emulated CPC applications: # Emulated brownfield OPC UA Server
   brownfield-opcua-server:
    container_name: brownfield-opcua-server
    build: rpi-brownfield-opcua-server/
    ports:
      - 4840:4840
      - 4841:4841
    attach: true

   ecotec-modbus-server:
    container_name: ecotec-modbus-server
    image: oitc/modbus-server:latest
    command: -f /server_config.json
    ports:
      - 503:503
    volumes:
      - ./rpi-modbustcp-server/server_config.json:/server_config.json:ro
    attach: true