services:

# Gateway-Applications:
  # Central M+O Application
  central-mo-client:
    container_name: central-mo-client
    build: central-mo-client/
    depends_on:
      interface-partition: 
        condition: service_started
    attach: true


  # Application of the gateway's Interface Partition
  interface-partition:
    container_name: interface-partition
    ipc: "service:cpc-partition"
    #ipc: "service:cpc-partition"
    build: interface-partition/
    # volumes:
    #   - type: bind
    #     source: ./interface-partition/user_manager/credentials.db
    #     target: /interface-partition/user_manager/credentials.db
    ports:
      - 4840:4840
    depends_on:
      cpc-partition: 
        condition: service_started
    attach: true


  # Intermediate VoR Partition
  intermediate-vor-partition:
    container_name: intermediate-vor-partition
    build: intermediate-vor-partition/
    ipc: "service:interface-partition"
    volumes:
      - type: bind
        source: ./intermediate-vor-partition/config/mapped_requests.db
        target: /app/config/mapped_requests.db
    depends_on:
      interface-partition: 
        condition: service_started
    attach: false

  # Second Intermediate VoR Partition (only temporary) TODO: remove
  intermediate-vor-partition-cpc:
    container_name: intermediate-vor-partition-cpc
    build: intermediate-vor-partition-cpc/
    #ipc: "service:interface-partition-cpc"
    volumes:
      - type: bind
        source: ./intermediate-vor-partition/config/mapped_requests.db
        target: /app/config/mapped_requests.db
      - type: bind
        source: ./intermediate-vor-partition-cpc/config/Acceptance_Ruleset_modified.xml
        target: /app/config/Acceptance_Ruleset_modified.xml
    depends_on:
      intermediate-vor-partition: 
        condition: service_started
    attach: false

  # Application of the gateway's psM+O Partition
  # emulates shared memory
  psmo-partition:
    container_name: psmo-partition
    ipc: "service:cpc-partition"
    build: psmo-partition/
    depends_on:
      cpc-partition: 
        condition: service_started
    attach: false

  # Application of the gateway's CPC Partition
  cpc-partition:
    container_name: cpc-partition 
    build: cpc-partition/
    ipc: "shareable"
    network_mode: "host"
    attach: true