services:

  # Application of the gateway's Interface Partition
  datenbereitstellung:
    container_name: datenbereitstellung
    ipc: "service:datenaggregation"
    build: datenbereitstellung/
    ports:
      - 4840:4840
    depends_on:
      datenaggregation: 
        condition: service_started
    attach: true

  # Intermediate VoR Partition  #Entwickelt von Yuanchen Zhao (IAT, RWTH Aachen)
  intermediate-vor-partition:
    container_name: intermediate-vor-partition
    build: intermediate-vor-partition/
    ipc: "service:datenbereitstellung"
    volumes:
      - type: bind
        source: ./intermediate-vor-partition/config/mapped_requests.db
        target: /app/config/mapped_requests.db
    depends_on:
      datenbereitstellung: 
        condition: service_started
    attach: false

  # Second Intermediate VoR Partition #Entwickelt von Yuanchen Zhao (IAT, RWTH Aachen)
  intermediate-vor-partition-cpc:
    container_name: intermediate-vor-partition-cpc
    build: intermediate-vor-partition-cpc/
    volumes:
      - type: bind
        source: ./intermediate-vor-partition/config/mapped_requests.db
        target: /app/config/mapped_requests.db
      - type: bind
        source: ./intermediate-vor-partition-cpc/config/Acceptance_Ruleset_modified.xml
        target: /app/config/Acceptance_Ruleset_modified.xml
    depends_on:
      intermediate-vor-partition: 
        condition: service_started
    attach: false

  # Application of the gateway's psM+O Partition
  psmo:
    container_name: psmo
    ipc: "service:datenaggregation"
    build: psmo/
    depends_on:
      datenaggregation: 
        condition: service_started
    attach: false

  # Application of the gateway's CPC Partition
  datenaggregation:
    container_name: datenaggregation 
    build: datenaggregation/
    ipc: "shareable"
    network_mode: "host"
    attach: true